server:
  port: 8443
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/white_jotter?serverTimezone=UTC%2b8
    username: root
    password: 1234
